sudo: false

language: java

jdk: openjdk12

before_deploy:
    - ./gradlew clean
    - ./gradlew test
    - ./gradlew jar

deploy:
    provider: releases
    api_key: $GIT_AUTH
    file_glob: true
    file: "build/libs/*"
    skip_cleanup: true
    prerelease: true
    name: Build $(date +'%d.%m.%Y %R')
    on:
        branch: master
        repo: HSLU-BaumannWicki/BDA_FS19-RFIDTestFramework
