sudo: false

language: java

addons:  
  sonarcloud:
    organization: "crydeb-github" # the key of the org you chose at step #3
    token:
      secure: $SONAR_AUTH # encrypted value of your token
  apt:
    packages:
      - openjdk-8-jdk:i386

before_deploy:
    - ./gradlew clean
    - sonar-scanner -Dsonar.sources=. -Dsonar.java.binaries=.
    - ./gradlew jar

deploy:
    provider: releases
    api_key: $GIT_AUTH
    file_glob: true
    file: "build/libs/*"
    skip_cleanup: true
    prerelease: true
    name: Build $(date +'%d.%m.%Y %R')
    on:
        branch: master
        repo: HSLU-BaumannWicki/BDA_FS19-RFIDTestFramework
