sudo: false

language: java

addons:
    apt:
        packages:
            - openjdk-8-jdk:i386

before_deploy:
    - ./gradlew clean
    - ./gradlew sonarqube -Dsonar.projectKey=CryDeb_BDA_FS19-RFIDTestFramework -Dsonar.organization=crydeb-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_AUTH
    - sonar-scanner -Dsonar.sources=. -Dsonar.java.binaries=.
    - ./gradlew test
    - ./gradlew jar

deploy:
    provider: releases
    api_key: $GIT_AUTH
    file_glob: true
    file: "build/libs/*"
    skip_cleanup: true
    prerelease: true
    name: Build $(date +'%d.%m.%Y %R')
    on:
        branch: master
        repo: HSLU-BaumannWicki/BDA_FS19-RFIDTestFramework
